# Generated by Django 2.1 on 2019-02-15 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_image', models.BinaryField()),
                ('employee_phone', models.CharField(max_length=10)),
                ('employee_address', models.TextField()),
                ('employee_gender', models.CharField(choices=[('--', '--'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='--', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
