# Generated by Django 2.1 on 2019-02-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
    ]
