# Generated by Django 2.1 on 2019-02-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image_link',
            field=models.CharField(default='hello', max_length=30),
            preserve_default=False,
        ),
    ]
