# Generated by Django 2.1 on 2019-02-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image_link',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_image',
            field=models.BinaryField(blank=True),
        ),
    ]
